[package]
name = "ict2024-bk07-stronghold-integration"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"  # Thêm dòng này vào phần phụ thuộc
[lib]
crate-type = ["cdylib"]  # Biên dịch thành WebAssembly
